# ScriptedLoadableModule.pyi
import vtk
from typing import Any, Optional, List

class ScriptedLoadableModule:
    parent: Any
    moduleName: str
    def __init__(self, parent: Any) -> None: ...

class ScriptedLoadableModuleWidget:
    parent: Any
    def __init__(self, parent: Optional[Any] = None) -> None: ...
    def setup(self) -> None: ...

class ScriptedLoadableModuleLogic:
    """Explicitly defined to avoid 'unbound' errors."""
    def __init__(self, parent: Optional[Any] = None) -> None: ...
    def createParameterNode(self) -> vtk.vtkMRMLScriptedModuleNode: ...
    def getParameterNode(self) -> vtk.vtkMRMLScriptedModuleNode: ...
    def getAllParameterNodes(self) -> List[vtk.vtkMRMLScriptedModuleNode]: ...

class ScriptedLoadableModuleTest:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
