from typing import Any, Iterable, Optional, Union


class PyQtSignal:
    def connect(self, receiverOrCallable: Any) -> None: ...
    def disconnect(self, receiverOrCallable: Any) -> None: ...
    def emit(self, *args: Any) -> None: ...


class QTimer:
    timeout: PyQtSignal  # This fixes the "Attribute unknown" error
    def __init__(self, parent: Any = ...) -> None: ...
    def start(self, msec: int = ...) -> None: ...
    def stop(self) -> None: ...
    def setInterval(self, msec: int) -> None: ...
    def setSingleShot(self, singleShot: bool) -> None: ...
    def isActive(self) -> bool: ...
    @staticmethod
    def singleShot(msec: int, receiverOrCallable: Any) -> None: ...

class Property:
    ...

class QAbstractAnimation:
    ...

class QAbstractAudioDeviceInfo:
    ...

class QAbstractAudioInput:
    ...

class QAbstractAudioOutput:
    ...

class QAbstractButton:
    ...

class QAbstractGraphicsShapeItem:
    ...

class QAbstractItemDelegate:
    ...

class QAbstractItemModel:
    ...

class QAbstractItemView:
    ...

class QAbstractListModel:
    ...

class QAbstractNetworkCache:
    ...

class QAbstractPrintDialog:
    ...

class QAbstractProxyModel:
    ...

class QAbstractScrollArea:
    ...

class QAbstractSlider:
    ...

class QAbstractSocket:
    ...

class QAbstractSpinBox:
    ...

class QAbstractState:
    ...

class QAbstractTableModel:
    ...

class QAbstractTextDocumentLayout:
    ...

class QAbstractTransition:
    ...

class QAbstractVideoBuffer:
    ...

class QAbstractVideoSurface:
    ...

class QAccessibleEvent:
    ...

class QAction:
    ...

class QActionEvent:
    ...

class QActionGroup:
    ...

class QAnimationGroup:
    ...

class QApplication:
    ...

class QApplicationStateChangeEvent:
    ...

class QAudio:
    ...

class QAudioBuffer:
    ...

class QAudioDecoder:
    ...

class QAudioDecoderControl:
    ...

class QAudioDeviceInfo:
    ...

class QAudioEncoderSettings:
    ...

class QAudioEncoderSettingsControl:
    ...

class QAudioFormat:
    ...

class QAudioInput:
    ...

class QAudioInputSelectorControl:
    ...

class QAudioOutput:
    ...

class QAudioOutputSelectorControl:
    ...

class QAudioProbe:
    ...

class QAudioRecorder:
    ...

class QAudioRoleControl:
    ...

class QAudioSystemFactoryInterface:
    ...

class QAudioSystemPlugin:
    ...

class QAuthenticator:
    ...

class QBackingStore:
    ...

class QBasicMutex:
    ...

class QBasicTimer:
    ...

class QBitArray:
    ...

class QBitmap:
    ...

class QBoxLayout:
    ...

class QBrush:
    ...

class QBuffer:
    ...

class QButtonGroup:
    ...

class QByteArray:
    ...

class QByteArrayMatcher:
    ...

class QCalendarWidget:
    ...

class QCamera:
    ...

class QCameraCaptureBufferFormatControl:
    ...

class QCameraCaptureDestinationControl:
    ...

class QCameraControl:
    ...

class QCameraExposure:
    ...

class QCameraExposureControl:
    ...

class QCameraFeedbackControl:
    ...

class QCameraFlashControl:
    ...

class QCameraFocus:
    ...

class QCameraFocusControl:
    ...

class QCameraFocusZone:
    ...

class QCameraImageCapture:
    ...

class QCameraImageCaptureControl:
    ...

class QCameraImageProcessing:
    ...

class QCameraImageProcessingControl:
    ...

class QCameraInfo:
    ...

class QCameraInfoControl:
    ...

class QCameraLocksControl:
    ...

class QCameraViewfinder:
    ...

class QCameraViewfinderSettings:
    ...

class QCameraViewfinderSettingsControl:
    ...

class QCameraViewfinderSettingsControl2:
    ...

class QCameraZoomControl:
    ...

class QCheckBox:
    ...

class QChildEvent:
    ...

class QClipboard:
    ...

class QCloseEvent:
    ...

class QCollator:
    ...

class QCollatorSortKey:
    ...

class QColor:
    ...

class QColorDialog:
    ...

class QColumnView:
    ...

class QComboBox:
    ...

class QCommandLineOption:
    ...

class QCommandLineParser:
    ...

class QCommandLinkButton:
    ...

class QCommonStyle:
    ...

class QCompleter:
    ...

class QConicalGradient:
    ...

class QContextMenuEvent:
    ...

class QCoreApplication:
    ...

class QCryptographicHash:
    ...

class QCursor:
    ...

class QDataStream:
    ...

class QDataWidgetMapper:
    ...

class QDate:
    ...

class QDateEdit:
    ...

class QDateTime:
    ...

class QDateTimeEdit:
    ...

class QDeadlineTimer:
    ...

class QDeferredDeleteEvent:
    ...

class QDesktopServices:
    ...

class QDesktopWidget:
    ...

class QDial:
    ...

class QDialog:
    ...

class QDialogButtonBox:
    ...

class QDir:
    ...

class QDirIterator:
    ...

class QDirModel:
    ...

class QDnsDomainNameRecord:
    ...

class QDnsHostAddressRecord:
    ...

class QDnsLookup:
    ...

class QDnsMailExchangeRecord:
    ...

class QDnsServiceRecord:
    ...

class QDnsTextRecord:
    ...

class QDockWidget:
    ...

class QDoubleSpinBox:
    ...

class QDoubleValidator:
    ...

class QDrag:
    ...

class QDragEnterEvent:
    ...

class QDragLeaveEvent:
    ...

class QDragMoveEvent:
    ...

class QDropEvent:
    ...

class QDynamicPropertyChangeEvent:
    ...

class QEasingCurve:
    ...

class QElapsedTimer:
    ...

class QEnterEvent:
    ...

class QErrorMessage:
    ...

class QEvent:
    ...

class QEventLoop:
    ...

class QEventTransition:
    ...

class QExposeEvent:
    ...

class QFactoryInterface:
    ...

class QFile:
    ...

class QFileDevice:
    ...

class QFileDialog:
    ...

class QFileIconProvider:
    ...

class QFileInfo:
    ...

class QFileOpenEvent:
    ...

class QFileSelector:
    ...

class QFileSystemModel:
    ...

class QFileSystemWatcher:
    ...

class QFinalState:
    ...

class QFocusEvent:
    ...

class QFocusFrame:
    ...

class QFont:
    ...

class QFontComboBox:
    ...

class QFontDatabase:
    ...

class QFontDialog:
    ...

class QFontInfo:
    ...

class QFontMetrics:
    ...

class QFontMetricsF:
    ...

class QFormLayout:
    ...

class QFrame:
    ...

class QGesture:
    ...

class QGestureEvent:
    ...

class QGestureRecognizer:
    ...

class QGlyphRun:
    ...

class QGradient:
    ...

class QGraphicsAnchor:
    ...

class QGraphicsAnchorLayout:
    ...

class QGraphicsBlurEffect:
    ...

class QGraphicsColorizeEffect:
    ...

class QGraphicsDropShadowEffect:
    ...

class QGraphicsEffect:
    ...

class QGraphicsEllipseItem:
    ...

class QGraphicsGridLayout:
    ...

class QGraphicsItem:
    ...

class QGraphicsItemAnimation:
    ...

class QGraphicsItemGroup:
    ...

class QGraphicsLayout:
    ...

class QGraphicsLayoutItem:
    ...

class QGraphicsLineItem:
    ...

class QGraphicsLinearLayout:
    ...

class QGraphicsObject:
    ...

class QGraphicsOpacityEffect:
    ...

class QGraphicsPathItem:
    ...

class QGraphicsPixmapItem:
    ...

class QGraphicsPolygonItem:
    ...

class QGraphicsProxyWidget:
    ...

class QGraphicsRectItem:
    ...

class QGraphicsRotation:
    ...

class QGraphicsScale:
    ...

class QGraphicsScene:
    ...

class QGraphicsSceneContextMenuEvent:
    ...

class QGraphicsSceneDragDropEvent:
    ...

class QGraphicsSceneEvent:
    ...

class QGraphicsSceneHelpEvent:
    ...

class QGraphicsSceneHoverEvent:
    ...

class QGraphicsSceneMouseEvent:
    ...

class QGraphicsSceneMoveEvent:
    ...

class QGraphicsSceneResizeEvent:
    ...

class QGraphicsSceneWheelEvent:
    ...

class QGraphicsSimpleTextItem:
    ...

class QGraphicsTextItem:
    ...

class QGraphicsTransform:
    ...

class QGraphicsVideoItem:
    ...

class QGraphicsView:
    ...

class QGraphicsWidget:
    ...

class QGridLayout:
    ...

class QGroupBox:
    ...

class QGuiApplication:
    ...

class QHBoxLayout:
    ...

class QHeaderView:
    ...

class QHelpEvent:
    ...

class QHideEvent:
    ...

class QHistoryState:
    ...

class QHostAddress:
    ...

class QHostInfo:
    ...

class QHoverEvent:
    ...

class QHstsPolicy:
    ...

class QHttpMultiPart:
    ...

class QHttpPart:
    ...

class QIODevice:
    ...

class QIPv6Address:
    ...

class QIcon:
    ...

class QIconDragEvent:
    ...

class QIconEngine:
    ...

class QIdentityProxyModel:
    ...

class QImage:
    ...

class QImageEncoderControl:
    ...

class QImageEncoderSettings:
    ...

class QImageIOHandler:
    ...

class QImageIOPlugin:
    ...

class QImageReader:
    ...

class QImageWriter:
    ...

class QInputDialog:
    ...

class QInputEvent:
    ...

class QInputMethod:
    ...

class QInputMethodEvent:
    ...

class QInputMethodQueryEvent:
    ...

class QIntValidator:
    ...

class QItemDelegate:
    ...

class QItemEditorCreatorBase:
    ...

class QItemEditorFactory:
    ...

class QItemSelection:
    ...

class QItemSelectionModel:
    ...

class QItemSelectionRange:
    ...

class QJsonArray:
    ...

class QJsonDocument:
    ...

class QJsonObject:
    ...

class QJsonParseError:
    ...

class QJsonValue:
    ...

class QKeyEvent:
    ...

class QKeyEventTransition:
    ...

class QKeySequence:
    ...

class QKeySequenceEdit:
    ...

class QLCDNumber:
    ...

class QLabel:
    ...

class QLayout:
    ...

class QLayoutItem:
    ...

class QLibrary:
    ...

class QLibraryInfo:
    ...

class QLine:
    ...

class QLineEdit:
    ...

class QLineF:
    ...

class QLinearGradient:
    ...

class QListView:
    ...

class QListWidget:
    ...

class QListWidgetItem:
    ...

class QLocalServer:
    ...

class QLocalSocket:
    ...

class QLocale:
    ...

class QLockFile:
    ...

class QMainWindow:
    ...

class QMargins:
    ...

class QMarginsF:
    ...

class QMatrix:
    ...

class QMatrix4x4:
    ...

class QMdiArea:
    ...

class QMdiSubWindow:
    ...

class QMediaAudioProbeControl:
    ...

class QMediaAvailabilityControl:
    ...

class QMediaBindableInterface:
    ...

class QMediaContainerControl:
    ...

class QMediaContent:
    ...

class QMediaControl:
    ...

class QMediaGaplessPlaybackControl:
    ...

class QMediaNetworkAccessControl:
    ...

class QMediaObject:
    ...

class QMediaPlayer:
    ...

class QMediaPlayerControl:
    ...

class QMediaPlaylist:
    ...

class QMediaRecorder:
    ...

class QMediaRecorderControl:
    ...

class QMediaResource:
    ...

class QMediaService:
    ...

class QMediaServiceCameraInfoInterface:
    ...

class QMediaServiceDefaultDeviceInterface:
    ...

class QMediaServiceProviderFactoryInterface:
    ...

class QMediaServiceProviderHint:
    ...

class QMediaServiceProviderPlugin:
    ...

class QMediaServiceSupportedDevicesInterface:
    ...

class QMediaServiceSupportedFormatsInterface:
    ...

class QMediaStreamsControl:
    ...

class QMediaTimeInterval:
    ...

class QMediaTimeRange:
    ...

class QMediaVideoProbeControl:
    ...

class QMenu:
    ...

class QMenuBar:
    ...

class QMessageAuthenticationCode:
    ...

class QMessageBox:
    ...

class QMessageLogContext:
    ...

class QMessageLogger:
    ...

class QMetaClassInfo:
    ...

class QMetaDataReaderControl:
    ...

class QMetaDataWriterControl:
    ...

class QMetaEnum:
    ...

class QMetaMethod:
    ...

class QMetaObject:
    ...

class QMetaProperty:
    ...

class QMetaType:
    ...

class QMimeData:
    ...

class QMimeDatabase:
    ...

class QMimeType:
    ...

class QModelIndex:
    ...

class QMouseEvent:
    ...

class QMouseEventTransition:
    ...

class QMoveEvent:
    ...

class QMovie:
    ...

class QMultimedia:
    ...

class QMutex:
    ...

class QNativeGestureEvent:
    ...

class QNetworkAccessManager:
    ...

class QNetworkAddressEntry:
    ...

class QNetworkCacheMetaData:
    ...

class QNetworkConfiguration:
    ...

class QNetworkConfigurationManager:
    ...

class QNetworkCookie:
    ...

class QNetworkCookieJar:
    ...

class QNetworkDatagram:
    ...

class QNetworkDiskCache:
    ...

class QNetworkInterface:
    ...

class QNetworkProxy:
    ...

class QNetworkProxyFactory:
    ...

class QNetworkProxyQuery:
    ...

class QNetworkReply:
    ...

class QNetworkRequest:
    ...

class QNetworkSession:
    ...

class QObject:
    ...

class QOffscreenSurface:
    ...

class QOpenGLBuffer:
    ...

class QOpenGLContext:
    ...

class QOpenGLContextGroup:
    ...

class QOpenGLFramebufferObject:
    ...

class QOpenGLFramebufferObjectFormat:
    ...

class QOpenGLPaintDevice:
    ...

class QOpenGLShader:
    ...

class QOpenGLShaderProgram:
    ...

class QOpenGLTexture:
    ...

class QOpenGLTextureBlitter:
    ...

class QOpenGLTimeMonitor:
    ...

class QOpenGLTimerQuery:
    ...

class QOpenGLVersionProfile:
    ...

class QOpenGLVertexArrayObject:
    ...

class QOpenGLWidget:
    ...

class QOpenGLWindow:
    ...

class QOperatingSystemVersion:
    ...

class QPageLayout:
    ...

class QPageSetupDialog:
    ...

class QPageSize:
    ...

class QPagedPaintDevice:
    ...

class QPaintDevice:
    ...

class QPaintDeviceWindow:
    ...

class QPaintEngine:
    ...

class QPaintEngineState:
    ...

class QPaintEvent:
    ...

class QPainter:
    ...

class QPainterPath:
    ...

class QPainterPathStroker:
    ...

class QPalette:
    ...

class QPanGesture:
    ...

class QParallelAnimationGroup:
    ...

class QPauseAnimation:
    ...

class QPdfWriter:
    ...

class QPen:
    ...

class QPersistentModelIndex:
    ...

class QPicture:
    ...

class QPictureFormatPlugin:
    ...

class QPictureIO:
    ...

class QPinchGesture:
    ...

class QPixelFormat:
    ...

class QPixmap:
    ...

class QPixmapCache:
    ...

class QPlainTextDocumentLayout:
    ...

class QPlainTextEdit:
    ...

class QPlatformSurfaceEvent:
    ...

class QPoint:
    ...

class QPointF:
    ...

class QPolygon:
    ...

class QPolygonF:
    ...

class QPrintDialog:
    ...

class QPrintEngine:
    ...

class QPrintPreviewDialog:
    ...

class QPrintPreviewWidget:
    ...

class QPrinter:
    ...

class QPrinterInfo:
    ...

class QProcess:
    ...

class QProcessEnvironment:
    ...

class QProgressBar:
    ...

class QProgressDialog:
    ...

class QPropertyAnimation:
    ...

class QProxyStyle:
    ...

class QPushButton:
    ...

class QQuaternion:
    ...

class QRadialGradient:
    ...

class QRadioButton:
    ...

class QRadioData:
    ...

class QRadioDataControl:
    ...

class QRadioTuner:
    ...

class QRadioTunerControl:
    ...

class QRandomGenerator:
    ...

class QRandomGenerator64:
    ...

class QRasterWindow:
    ...

class QRawFont:
    ...

class QReadWriteLock:
    ...

class QRect:
    ...

class QRectF:
    ...

class QRegExp:
    ...

class QRegExpValidator:
    ...

class QRegion:
    ...

class QRegularExpression:
    ...

class QRegularExpressionMatch:
    ...

class QRegularExpressionMatchIterator:
    ...

class QRegularExpressionValidator:
    ...

class QResizeEvent:
    ...

class QResource:
    ...

class QRgba64:
    ...

class QRubberBand:
    ...

class QRunnable:
    ...

class QSaveFile:
    ...

class QScreen:
    ...

class QScreenOrientationChangeEvent:
    ...

class QScrollArea:
    ...

class QScrollBar:
    ...

class QScrollEvent:
    ...

class QScrollPrepareEvent:
    ...

class QScroller:
    ...

class QScrollerProperties:
    ...

class QSemaphore:
    ...

class QSequentialAnimationGroup:
    ...

class QSessionManager:
    ...

class QSettings:
    ...

class QSharedMemory:
    ...

class QShortcut:
    ...

class QShortcutEvent:
    ...

class QShowEvent:
    ...

class QSignalBlocker:
    ...

class QSignalMapper:
    ...

class QSignalTransition:
    ...

class QSize:
    ...

class QSizeF:
    ...

class QSizeGrip:
    ...

class QSizePolicy:
    ...

class QSlider:
    ...

class QSocketNotifier:
    ...

class QSortFilterProxyModel:
    ...

class QSound:
    ...

class QSoundEffect:
    ...

class QSpacerItem:
    ...

class QSpinBox:
    ...

class QSplashScreen:
    ...

class QSplitter:
    ...

class QSplitterHandle:
    ...

class QSsl:
    ...

class QSslCertificate:
    ...

class QSslCertificateExtension:
    ...

class QSslCipher:
    ...

class QSslConfiguration:
    ...

class QSslEllipticCurve:
    ...

class QSslError:
    ...

class QSslKey:
    ...

class QSslPreSharedKeyAuthenticator:
    ...

class QSslSocket:
    ...

class QStackedLayout:
    ...

class QStackedWidget:
    ...

class QStandardItem:
    ...

class QStandardItemModel:
    ...

class QStandardPaths:
    ...

class QState:
    ...

class QStateMachine:
    ...

class QStaticText:
    ...

class QStatusBar:
    ...

class QStatusTipEvent:
    ...

class QStorageInfo:
    ...

class QStringListModel:
    ...

class QStringMatcher:
    ...

class QStyle:
    ...

class QStyleFactory:
    ...

class QStyleHintReturn:
    ...

class QStyleHintReturnMask:
    ...

class QStyleHintReturnVariant:
    ...

class QStyleHints:
    ...

class QStyleOption:
    ...

class QStyleOptionButton:
    ...

class QStyleOptionComboBox:
    ...

class QStyleOptionDockWidget:
    ...

class QStyleOptionDockWidgetV2:
    ...

class QStyleOptionFocusRect:
    ...

class QStyleOptionFrame:
    ...

class QStyleOptionFrameV2:
    ...

class QStyleOptionFrameV3:
    ...

class QStyleOptionGraphicsItem:
    ...

class QStyleOptionGroupBox:
    ...

class QStyleOptionHeader:
    ...

class QStyleOptionMenuItem:
    ...

class QStyleOptionProgressBar:
    ...

class QStyleOptionProgressBarV2:
    ...

class QStyleOptionRubberBand:
    ...

class QStyleOptionSizeGrip:
    ...

class QStyleOptionSlider:
    ...

class QStyleOptionSpinBox:
    ...

class QStyleOptionTab:
    ...

class QStyleOptionTabBarBase:
    ...

class QStyleOptionTabBarBaseV2:
    ...

class QStyleOptionTabV2:
    ...

class QStyleOptionTabV3:
    ...

class QStyleOptionTabWidgetFrame:
    ...

class QStyleOptionTabWidgetFrameV2:
    ...

class QStyleOptionTitleBar:
    ...

class QStyleOptionToolBar:
    ...

class QStyleOptionToolBox:
    ...

class QStyleOptionToolBoxV2:
    ...

class QStyleOptionToolButton:
    ...

class QStyleOptionViewItem:
    ...

class QStyleOptionViewItemV2:
    ...

class QStyleOptionViewItemV3:
    ...

class QStyleOptionViewItemV4:
    ...

class QStylePainter:
    ...

class QStylePlugin:
    ...

class QStyledItemDelegate:
    ...

class QSurface:
    ...

class QSurfaceFormat:
    ...

class QSwipeGesture:
    ...

class QSyntaxHighlighter:
    ...

class QSysInfo:
    ...

class QSystemSemaphore:
    ...

class QSystemTrayIcon:
    ...

class QTabBar:
    ...

class QTabWidget:
    ...

class QTableView:
    ...

class QTableWidget:
    ...

class QTableWidgetItem:
    ...

class QTableWidgetSelectionRange:
    ...

class QTabletEvent:
    ...

class QTapAndHoldGesture:
    ...

class QTapGesture:
    ...

class QTcpServer:
    ...

class QTcpSocket:
    ...

class QTemporaryDir:
    ...

class QTemporaryFile:
    ...

class QTextBlock:
    ...

class QTextBlockFormat:
    ...

class QTextBlockGroup:
    ...

class QTextBlockUserData:
    ...

class QTextBoundaryFinder:
    ...

class QTextBrowser:
    ...

class QTextCharFormat:
    ...

class QTextCodec:
    ...

class QTextCursor:
    ...

class QTextDecoder:
    ...

class QTextDocument:
    ...

class QTextDocumentFragment:
    ...

class QTextDocumentWriter:
    ...

class QTextEdit:
    ...

class QTextEncoder:
    ...

class QTextFormat:
    ...

class QTextFragment:
    ...

class QTextFrame:
    ...

class QTextFrameFormat:
    ...

class QTextImageFormat:
    ...

class QTextInlineObject:
    ...

class QTextItem:
    ...

class QTextLayout:
    ...

class QTextLength:
    ...

class QTextLine:
    ...

class QTextList:
    ...

class QTextListFormat:
    ...

class QTextObject:
    ...

class QTextOption:
    ...

class QTextStream:
    ...

class QTextTable:
    ...

class QTextTableCell:
    ...

class QTextTableCellFormat:
    ...

class QTextTableFormat:
    ...

class QThreadPool:
    ...

class QTileRules:
    ...

class QTime:
    ...

class QTimeEdit:
    ...

class QTimeLine:
    ...

class QTimeZone:
    ...

class QTimerEvent:
    ...

class QToolBar:
    ...

class QToolBarChangeEvent:
    ...

class QToolBox:
    ...

class QToolButton:
    ...

class QToolTip:
    ...

class QTouchDevice:
    ...

class QTouchEvent:
    ...

class QTransform:
    ...

class QTranslator:
    ...

class QTreeView:
    ...

class QTreeWidget:
    ...

class QTreeWidgetItem:
    ...

class QUdpSocket:
    ...

class QUiLoader:
    ...

class QUndoCommand:
    ...

class QUndoGroup:
    ...

class QUndoStack:
    ...

class QUndoView:
    ...

class QUrl:
    ...

class QUrlQuery:
    ...

class QUuid:
    ...

class QVBoxLayout:
    ...

class QValidator:
    ...

class QVariantAnimation:
    ...

class QVector2D:
    ...

class QVector3D:
    ...

class QVector4D:
    ...

class QVideoDeviceSelectorControl:
    ...

class QVideoEncoderSettings:
    ...

class QVideoEncoderSettingsControl:
    ...

class QVideoFrame:
    ...

class QVideoProbe:
    ...

class QVideoRendererControl:
    ...

class QVideoSurfaceFormat:
    ...

class QVideoWidget:
    ...

class QVideoWidgetControl:
    ...

class QVideoWindowControl:
    ...

class QWaitCondition:
    ...

class QWhatsThis:
    ...

class QWhatsThisClickedEvent:
    ...

class QWheelEvent:
    ...

class QWidget:
    ...

class QWidgetAction:
    ...

class QWidgetItem:
    ...

class QWindow:
    ...

class QWindowStateChangeEvent:
    ...

class QWizard:
    ...

class QWizardPage:
    ...

class QXmlStreamEntityResolver:
    ...

class Qt:
    ...

class Signal:
    ...

class Slot:
    ...


__all__ = ['PyQtSignal', 'QTimer', 'Property', 'QAbstractAnimation', 'QAbstractAudioDeviceInfo', 'QAbstractAudioInput', 'QAbstractAudioOutput', 'QAbstractButton', 'QAbstractGraphicsShapeItem', 'QAbstractItemDelegate', 'QAbstractItemModel', 'QAbstractItemView', 'QAbstractListModel', 'QAbstractNetworkCache', 'QAbstractPrintDialog', 'QAbstractProxyModel', 'QAbstractScrollArea', 'QAbstractSlider', 'QAbstractSocket', 'QAbstractSpinBox', 'QAbstractState', 'QAbstractTableModel', 'QAbstractTextDocumentLayout', 'QAbstractTransition', 'QAbstractVideoBuffer', 'QAbstractVideoSurface', 'QAccessibleEvent', 'QAction', 'QActionEvent', 'QActionGroup', 'QAnimationGroup', 'QApplication', 'QApplicationStateChangeEvent', 'QAudio', 'QAudioBuffer', 'QAudioDecoder', 'QAudioDecoderControl', 'QAudioDeviceInfo', 'QAudioEncoderSettings', 'QAudioEncoderSettingsControl', 'QAudioFormat', 'QAudioInput', 'QAudioInputSelectorControl', 'QAudioOutput', 'QAudioOutputSelectorControl', 'QAudioProbe', 'QAudioRecorder', 'QAudioRoleControl', 'QAudioSystemFactoryInterface', 'QAudioSystemPlugin', 'QAuthenticator', 'QBackingStore', 'QBasicMutex', 'QBasicTimer', 'QBitArray', 'QBitmap', 'QBoxLayout', 'QBrush', 'QBuffer', 'QButtonGroup', 'QByteArray', 'QByteArrayMatcher', 'QCalendarWidget', 'QCamera', 'QCameraCaptureBufferFormatControl', 'QCameraCaptureDestinationControl', 'QCameraControl', 'QCameraExposure', 'QCameraExposureControl', 'QCameraFeedbackControl', 'QCameraFlashControl', 'QCameraFocus', 'QCameraFocusControl', 'QCameraFocusZone', 'QCameraImageCapture', 'QCameraImageCaptureControl', 'QCameraImageProcessing', 'QCameraImageProcessingControl', 'QCameraInfo', 'QCameraInfoControl', 'QCameraLocksControl', 'QCameraViewfinder', 'QCameraViewfinderSettings', 'QCameraViewfinderSettingsControl', 'QCameraViewfinderSettingsControl2', 'QCameraZoomControl', 'QCheckBox', 'QChildEvent', 'QClipboard', 'QCloseEvent', 'QCollator', 'QCollatorSortKey', 'QColor', 'QColorDialog', 'QColumnView', 'QComboBox', 'QCommandLineOption', 'QCommandLineParser', 'QCommandLinkButton', 'QCommonStyle', 'QCompleter', 'QConicalGradient', 'QContextMenuEvent', 'QCoreApplication', 'QCryptographicHash', 'QCursor', 'QDataStream', 'QDataWidgetMapper', 'QDate', 'QDateEdit', 'QDateTime', 'QDateTimeEdit', 'QDeadlineTimer', 'QDeferredDeleteEvent', 'QDesktopServices', 'QDesktopWidget', 'QDial', 'QDialog', 'QDialogButtonBox', 'QDir', 'QDirIterator', 'QDirModel', 'QDnsDomainNameRecord', 'QDnsHostAddressRecord', 'QDnsLookup', 'QDnsMailExchangeRecord', 'QDnsServiceRecord', 'QDnsTextRecord', 'QDockWidget', 'QDoubleSpinBox', 'QDoubleValidator', 'QDrag', 'QDragEnterEvent', 'QDragLeaveEvent', 'QDragMoveEvent', 'QDropEvent', 'QDynamicPropertyChangeEvent', 'QEasingCurve', 'QElapsedTimer', 'QEnterEvent', 'QErrorMessage', 'QEvent', 'QEventLoop', 'QEventTransition', 'QExposeEvent', 'QFactoryInterface', 'QFile', 'QFileDevice', 'QFileDialog', 'QFileIconProvider', 'QFileInfo', 'QFileOpenEvent', 'QFileSelector', 'QFileSystemModel', 'QFileSystemWatcher', 'QFinalState', 'QFocusEvent', 'QFocusFrame', 'QFont', 'QFontComboBox', 'QFontDatabase', 'QFontDialog', 'QFontInfo', 'QFontMetrics', 'QFontMetricsF', 'QFormLayout', 'QFrame', 'QGesture', 'QGestureEvent', 'QGestureRecognizer', 'QGlyphRun', 'QGradient', 'QGraphicsAnchor', 'QGraphicsAnchorLayout', 'QGraphicsBlurEffect', 'QGraphicsColorizeEffect', 'QGraphicsDropShadowEffect', 'QGraphicsEffect', 'QGraphicsEllipseItem', 'QGraphicsGridLayout', 'QGraphicsItem', 'QGraphicsItemAnimation', 'QGraphicsItemGroup', 'QGraphicsLayout', 'QGraphicsLayoutItem', 'QGraphicsLineItem', 'QGraphicsLinearLayout', 'QGraphicsObject', 'QGraphicsOpacityEffect', 'QGraphicsPathItem', 'QGraphicsPixmapItem', 'QGraphicsPolygonItem', 'QGraphicsProxyWidget', 'QGraphicsRectItem', 'QGraphicsRotation', 'QGraphicsScale', 'QGraphicsScene', 'QGraphicsSceneContextMenuEvent', 'QGraphicsSceneDragDropEvent', 'QGraphicsSceneEvent', 'QGraphicsSceneHelpEvent', 'QGraphicsSceneHoverEvent', 'QGraphicsSceneMouseEvent', 'QGraphicsSceneMoveEvent', 'QGraphicsSceneResizeEvent', 'QGraphicsSceneWheelEvent', 'QGraphicsSimpleTextItem', 'QGraphicsTextItem', 'QGraphicsTransform', 'QGraphicsVideoItem', 'QGraphicsView', 'QGraphicsWidget', 'QGridLayout', 'QGroupBox', 'QGuiApplication', 'QHBoxLayout', 'QHeaderView', 'QHelpEvent', 'QHideEvent', 'QHistoryState', 'QHostAddress', 'QHostInfo', 'QHoverEvent', 'QHstsPolicy', 'QHttpMultiPart', 'QHttpPart', 'QIODevice', 'QIPv6Address', 'QIcon', 'QIconDragEvent', 'QIconEngine', 'QIdentityProxyModel', 'QImage', 'QImageEncoderControl', 'QImageEncoderSettings', 'QImageIOHandler', 'QImageIOPlugin', 'QImageReader', 'QImageWriter', 'QInputDialog', 'QInputEvent', 'QInputMethod', 'QInputMethodEvent', 'QInputMethodQueryEvent', 'QIntValidator', 'QItemDelegate', 'QItemEditorCreatorBase', 'QItemEditorFactory', 'QItemSelection', 'QItemSelectionModel', 'QItemSelectionRange', 'QJsonArray', 'QJsonDocument', 'QJsonObject', 'QJsonParseError', 'QJsonValue', 'QKeyEvent', 'QKeyEventTransition', 'QKeySequence', 'QKeySequenceEdit', 'QLCDNumber', 'QLabel', 'QLayout', 'QLayoutItem', 'QLibrary', 'QLibraryInfo', 'QLine', 'QLineEdit', 'QLineF', 'QLinearGradient', 'QListView', 'QListWidget', 'QListWidgetItem', 'QLocalServer', 'QLocalSocket', 'QLocale', 'QLockFile', 'QMainWindow', 'QMargins', 'QMarginsF', 'QMatrix', 'QMatrix4x4', 'QMdiArea', 'QMdiSubWindow', 'QMediaAudioProbeControl', 'QMediaAvailabilityControl', 'QMediaBindableInterface', 'QMediaContainerControl', 'QMediaContent', 'QMediaControl', 'QMediaGaplessPlaybackControl', 'QMediaNetworkAccessControl', 'QMediaObject', 'QMediaPlayer', 'QMediaPlayerControl', 'QMediaPlaylist', 'QMediaRecorder', 'QMediaRecorderControl', 'QMediaResource', 'QMediaService', 'QMediaServiceCameraInfoInterface', 'QMediaServiceDefaultDeviceInterface', 'QMediaServiceProviderFactoryInterface', 'QMediaServiceProviderHint', 'QMediaServiceProviderPlugin', 'QMediaServiceSupportedDevicesInterface', 'QMediaServiceSupportedFormatsInterface', 'QMediaStreamsControl', 'QMediaTimeInterval', 'QMediaTimeRange', 'QMediaVideoProbeControl', 'QMenu', 'QMenuBar', 'QMessageAuthenticationCode', 'QMessageBox', 'QMessageLogContext', 'QMessageLogger', 'QMetaClassInfo', 'QMetaDataReaderControl', 'QMetaDataWriterControl', 'QMetaEnum', 'QMetaMethod', 'QMetaObject', 'QMetaProperty', 'QMetaType', 'QMimeData', 'QMimeDatabase', 'QMimeType', 'QModelIndex', 'QMouseEvent', 'QMouseEventTransition', 'QMoveEvent', 'QMovie', 'QMultimedia', 'QMutex', 'QNativeGestureEvent', 'QNetworkAccessManager', 'QNetworkAddressEntry', 'QNetworkCacheMetaData', 'QNetworkConfiguration', 'QNetworkConfigurationManager', 'QNetworkCookie', 'QNetworkCookieJar', 'QNetworkDatagram', 'QNetworkDiskCache', 'QNetworkInterface', 'QNetworkProxy', 'QNetworkProxyFactory', 'QNetworkProxyQuery', 'QNetworkReply', 'QNetworkRequest', 'QNetworkSession', 'QObject', 'QOffscreenSurface', 'QOpenGLBuffer', 'QOpenGLContext', 'QOpenGLContextGroup', 'QOpenGLFramebufferObject', 'QOpenGLFramebufferObjectFormat', 'QOpenGLPaintDevice', 'QOpenGLShader', 'QOpenGLShaderProgram', 'QOpenGLTexture', 'QOpenGLTextureBlitter', 'QOpenGLTimeMonitor', 'QOpenGLTimerQuery', 'QOpenGLVersionProfile', 'QOpenGLVertexArrayObject', 'QOpenGLWidget', 'QOpenGLWindow', 'QOperatingSystemVersion', 'QPageLayout', 'QPageSetupDialog', 'QPageSize', 'QPagedPaintDevice', 'QPaintDevice', 'QPaintDeviceWindow', 'QPaintEngine', 'QPaintEngineState', 'QPaintEvent', 'QPainter', 'QPainterPath', 'QPainterPathStroker', 'QPalette', 'QPanGesture', 'QParallelAnimationGroup', 'QPauseAnimation', 'QPdfWriter', 'QPen', 'QPersistentModelIndex', 'QPicture', 'QPictureFormatPlugin', 'QPictureIO', 'QPinchGesture', 'QPixelFormat', 'QPixmap', 'QPixmapCache', 'QPlainTextDocumentLayout', 'QPlainTextEdit', 'QPlatformSurfaceEvent', 'QPoint', 'QPointF', 'QPolygon', 'QPolygonF', 'QPrintDialog', 'QPrintEngine', 'QPrintPreviewDialog', 'QPrintPreviewWidget', 'QPrinter', 'QPrinterInfo', 'QProcess', 'QProcessEnvironment', 'QProgressBar', 'QProgressDialog', 'QPropertyAnimation', 'QProxyStyle', 'QPushButton', 'QQuaternion', 'QRadialGradient', 'QRadioButton', 'QRadioData', 'QRadioDataControl', 'QRadioTuner', 'QRadioTunerControl', 'QRandomGenerator', 'QRandomGenerator64', 'QRasterWindow', 'QRawFont', 'QReadWriteLock', 'QRect', 'QRectF', 'QRegExp', 'QRegExpValidator', 'QRegion', 'QRegularExpression', 'QRegularExpressionMatch', 'QRegularExpressionMatchIterator', 'QRegularExpressionValidator', 'QResizeEvent', 'QResource', 'QRgba64', 'QRubberBand', 'QRunnable', 'QSaveFile', 'QScreen', 'QScreenOrientationChangeEvent', 'QScrollArea', 'QScrollBar', 'QScrollEvent', 'QScrollPrepareEvent', 'QScroller', 'QScrollerProperties', 'QSemaphore', 'QSequentialAnimationGroup', 'QSessionManager', 'QSettings', 'QSharedMemory', 'QShortcut', 'QShortcutEvent', 'QShowEvent', 'QSignalBlocker', 'QSignalMapper', 'QSignalTransition', 'QSize', 'QSizeF', 'QSizeGrip', 'QSizePolicy', 'QSlider', 'QSocketNotifier', 'QSortFilterProxyModel', 'QSound', 'QSoundEffect', 'QSpacerItem', 'QSpinBox', 'QSplashScreen', 'QSplitter', 'QSplitterHandle', 'QSsl', 'QSslCertificate', 'QSslCertificateExtension', 'QSslCipher', 'QSslConfiguration', 'QSslEllipticCurve', 'QSslError', 'QSslKey', 'QSslPreSharedKeyAuthenticator', 'QSslSocket', 'QStackedLayout', 'QStackedWidget', 'QStandardItem', 'QStandardItemModel', 'QStandardPaths', 'QState', 'QStateMachine', 'QStaticText', 'QStatusBar', 'QStatusTipEvent', 'QStorageInfo', 'QStringListModel', 'QStringMatcher', 'QStyle', 'QStyleFactory', 'QStyleHintReturn', 'QStyleHintReturnMask', 'QStyleHintReturnVariant', 'QStyleHints', 'QStyleOption', 'QStyleOptionButton', 'QStyleOptionComboBox', 'QStyleOptionDockWidget', 'QStyleOptionDockWidgetV2', 'QStyleOptionFocusRect', 'QStyleOptionFrame', 'QStyleOptionFrameV2', 'QStyleOptionFrameV3', 'QStyleOptionGraphicsItem', 'QStyleOptionGroupBox', 'QStyleOptionHeader', 'QStyleOptionMenuItem', 'QStyleOptionProgressBar', 'QStyleOptionProgressBarV2', 'QStyleOptionRubberBand', 'QStyleOptionSizeGrip', 'QStyleOptionSlider', 'QStyleOptionSpinBox', 'QStyleOptionTab', 'QStyleOptionTabBarBase', 'QStyleOptionTabBarBaseV2', 'QStyleOptionTabV2', 'QStyleOptionTabV3', 'QStyleOptionTabWidgetFrame', 'QStyleOptionTabWidgetFrameV2', 'QStyleOptionTitleBar', 'QStyleOptionToolBar', 'QStyleOptionToolBox', 'QStyleOptionToolBoxV2', 'QStyleOptionToolButton', 'QStyleOptionViewItem', 'QStyleOptionViewItemV2', 'QStyleOptionViewItemV3', 'QStyleOptionViewItemV4', 'QStylePainter', 'QStylePlugin', 'QStyledItemDelegate', 'QSurface', 'QSurfaceFormat', 'QSwipeGesture', 'QSyntaxHighlighter', 'QSysInfo', 'QSystemSemaphore', 'QSystemTrayIcon', 'QTabBar', 'QTabWidget', 'QTableView', 'QTableWidget', 'QTableWidgetItem', 'QTableWidgetSelectionRange', 'QTabletEvent', 'QTapAndHoldGesture', 'QTapGesture', 'QTcpServer', 'QTcpSocket', 'QTemporaryDir', 'QTemporaryFile', 'QTextBlock', 'QTextBlockFormat', 'QTextBlockGroup', 'QTextBlockUserData', 'QTextBoundaryFinder', 'QTextBrowser', 'QTextCharFormat', 'QTextCodec', 'QTextCursor', 'QTextDecoder', 'QTextDocument', 'QTextDocumentFragment', 'QTextDocumentWriter', 'QTextEdit', 'QTextEncoder', 'QTextFormat', 'QTextFragment', 'QTextFrame', 'QTextFrameFormat', 'QTextImageFormat', 'QTextInlineObject', 'QTextItem', 'QTextLayout', 'QTextLength', 'QTextLine', 'QTextList', 'QTextListFormat', 'QTextObject', 'QTextOption', 'QTextStream', 'QTextTable', 'QTextTableCell', 'QTextTableCellFormat', 'QTextTableFormat', 'QThreadPool', 'QTileRules', 'QTime', 'QTimeEdit', 'QTimeLine', 'QTimeZone', 'QTimerEvent', 'QToolBar', 'QToolBarChangeEvent', 'QToolBox', 'QToolButton', 'QToolTip', 'QTouchDevice', 'QTouchEvent', 'QTransform', 'QTranslator', 'QTreeView', 'QTreeWidget', 'QTreeWidgetItem', 'QUdpSocket', 'QUiLoader', 'QUndoCommand', 'QUndoGroup', 'QUndoStack', 'QUndoView', 'QUrl', 'QUrlQuery', 'QUuid', 'QVBoxLayout', 'QValidator', 'QVariantAnimation', 'QVector2D', 'QVector3D', 'QVector4D', 'QVideoDeviceSelectorControl', 'QVideoEncoderSettings', 'QVideoEncoderSettingsControl', 'QVideoFrame', 'QVideoProbe', 'QVideoRendererControl', 'QVideoSurfaceFormat', 'QVideoWidget', 'QVideoWidgetControl', 'QVideoWindowControl', 'QWaitCondition', 'QWhatsThis', 'QWhatsThisClickedEvent', 'QWheelEvent', 'QWidget', 'QWidgetAction', 'QWidgetItem', 'QWindow', 'QWindowStateChangeEvent', 'QWizard', 'QWizardPage', 'QXmlStreamEntityResolver', 'Qt', 'Signal', 'Slot']
