from typing import Any

# This allows slicer.modules, slicer.util, slicer.mrmlScene, etc.
def __getattr__(name: str) -> Any: ...

# Explicitly defining modules for better autocomplete experience
class modules(Any):
    def __getattr__(self, name: str) -> Any: ...

# Common Slicer classes often used in modules
class qSlicerWidget(Any): ...
class qMRMLNodeComboBox(Any): ...
